### ISSUE TITLE
Getting Started CLI - CF Specific

### ISSUE THREAD

**Issue by jenmlin** [ibm-cloud-docs/cli#109]
https://cloud.ibm.com/docs/cli?topic=cloud-cli-getting-started#step3-configure-idt-env

Because you may set up the CLI for resources that don't utilize Cloud Foundry - Can we remove this from the Getting Started?

**Comment by cjcarpen** [comment]
Thanks for your feedback, @jenmlin ! Because Cloud Foundry is a common use case for beginners on IBM Cloud and with the CLI, we'd like to keep it in the getting started tutorial. We've updated the wording in that step to make it clearer that it's optional and only necessary if you plan to work with Cloud Foundry.

https://cloud.ibm.com/docs/cli?topic=cloud-cli-getting-started#step3-configure-idt-env
